// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trace/trace.proto

package trace

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type__       Type = 0
	Type_Send    Type = 1
	Type_Receive Type = 2
)

var Type_name = map[int32]string{
	0: "_",
	1: "Send",
	2: "Receive",
}

var Type_value = map[string]int32{
	"_":       0,
	"Send":    1,
	"Receive": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3e383dd2cfd68a4a, []int{0}
}

type Data struct {
	Type                 Type     `protobuf:"varint,1,opt,name=type,proto3,enum=trace.Type" json:"type,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageName          string   `protobuf:"bytes,3,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	Previous             *Data    `protobuf:"bytes,10,opt,name=previous,proto3" json:"previous,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e383dd2cfd68a4a, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type__
}

func (m *Data) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Data) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *Data) GetPrevious() *Data {
	if m != nil {
		return m.Previous
	}
	return nil
}

type Chain struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Depth                int64    `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	Data                 *Data    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Rlfi                 *RLFI    `protobuf:"bytes,20,opt,name=rlfi,proto3" json:"rlfi,omitempty"`
	Tfi                  *TFI     `protobuf:"bytes,21,opt,name=tfi,proto3" json:"tfi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e383dd2cfd68a4a, []int{1}
}

func (m *Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain.Unmarshal(m, b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return xxx_messageInfo_Chain.Size(m)
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Chain) GetDepth() int64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *Chain) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Chain) GetRlfi() *RLFI {
	if m != nil {
		return m.Rlfi
	}
	return nil
}

func (m *Chain) GetTfi() *TFI {
	if m != nil {
		return m.Tfi
	}
	return nil
}

type RLFI struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RLFI) Reset()         { *m = RLFI{} }
func (m *RLFI) String() string { return proto.CompactTextString(m) }
func (*RLFI) ProtoMessage()    {}
func (*RLFI) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e383dd2cfd68a4a, []int{2}
}

func (m *RLFI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RLFI.Unmarshal(m, b)
}
func (m *RLFI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RLFI.Marshal(b, m, deterministic)
}
func (m *RLFI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RLFI.Merge(m, src)
}
func (m *RLFI) XXX_Size() int {
	return xxx_messageInfo_RLFI.Size(m)
}
func (m *RLFI) XXX_DiscardUnknown() {
	xxx_messageInfo_RLFI.DiscardUnknown(m)
}

var xxx_messageInfo_RLFI proto.InternalMessageInfo

func (m *RLFI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TFI struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	After                []string `protobuf:"bytes,2,rep,name=after,proto3" json:"after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFI) Reset()         { *m = TFI{} }
func (m *TFI) String() string { return proto.CompactTextString(m) }
func (*TFI) ProtoMessage()    {}
func (*TFI) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e383dd2cfd68a4a, []int{3}
}

func (m *TFI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFI.Unmarshal(m, b)
}
func (m *TFI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFI.Marshal(b, m, deterministic)
}
func (m *TFI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFI.Merge(m, src)
}
func (m *TFI) XXX_Size() int {
	return xxx_messageInfo_TFI.Size(m)
}
func (m *TFI) XXX_DiscardUnknown() {
	xxx_messageInfo_TFI.DiscardUnknown(m)
}

var xxx_messageInfo_TFI proto.InternalMessageInfo

func (m *TFI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TFI) GetAfter() []string {
	if m != nil {
		return m.After
	}
	return nil
}

func init() {
	proto.RegisterEnum("trace.Type", Type_name, Type_value)
	proto.RegisterType((*Data)(nil), "trace.Data")
	proto.RegisterType((*Chain)(nil), "trace.Chain")
	proto.RegisterType((*RLFI)(nil), "trace.RLFI")
	proto.RegisterType((*TFI)(nil), "trace.TFI")
}

func init() { proto.RegisterFile("trace/trace.proto", fileDescriptor_3e383dd2cfd68a4a) }

var fileDescriptor_3e383dd2cfd68a4a = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xff, 0x69, 0xd3, 0xbf, 0xdb, 0xad, 0x8c, 0x79, 0x99, 0x10, 0x64, 0x60, 0x2d, 0x82,
	0xc5, 0x87, 0x0d, 0xf4, 0x23, 0x28, 0x83, 0x81, 0xf8, 0x10, 0xf7, 0x3e, 0xe2, 0x7a, 0xe7, 0x02,
	0x76, 0x0b, 0x6d, 0x1c, 0xec, 0x43, 0xf8, 0xe0, 0x37, 0x96, 0xdc, 0xce, 0x89, 0xe2, 0x4b, 0xe9,
	0xbd, 0xbf, 0x43, 0xce, 0x39, 0x09, 0x9c, 0xf8, 0xda, 0x2c, 0x68, 0xcc, 0xdf, 0x91, 0xab, 0x37,
	0x7e, 0x83, 0x09, 0x0f, 0xf9, 0x87, 0x00, 0x79, 0x6f, 0xbc, 0xc1, 0x73, 0x90, 0x7e, 0xe7, 0x48,
	0x89, 0x4c, 0x14, 0xbd, 0x9b, 0x74, 0xd4, 0x6a, 0x67, 0x3b, 0x47, 0x9a, 0x01, 0x0e, 0xa1, 0xeb,
	0x6d, 0x45, 0x8d, 0x37, 0x95, 0x53, 0x51, 0x26, 0x8a, 0x58, 0x7f, 0x2f, 0xf0, 0x02, 0x8e, 0x2b,
	0x6a, 0x1a, 0xf3, 0x42, 0xf3, 0xb5, 0xa9, 0x48, 0xc5, 0x99, 0x28, 0xba, 0x3a, 0xdd, 0xef, 0x1e,
	0x4d, 0x45, 0x78, 0x05, 0x1d, 0x57, 0xd3, 0xd6, 0x6e, 0xde, 0x1a, 0x05, 0x99, 0x28, 0xd2, 0x83,
	0x4b, 0x08, 0xa0, 0x0f, 0x30, 0x7f, 0x17, 0x90, 0xdc, 0xad, 0x8c, 0x5d, 0x63, 0x0f, 0x22, 0x5b,
	0x72, 0xa4, 0x58, 0x47, 0xb6, 0xc4, 0x01, 0x24, 0x25, 0x39, 0xbf, 0xda, 0xfb, 0xb7, 0x43, 0x88,
	0x5e, 0x1a, 0x6f, 0xd8, 0xf3, 0xd7, 0xa1, 0x0c, 0x82, 0xa0, 0x7e, 0x5d, 0x5a, 0x35, 0xf8, 0x21,
	0xd0, 0x0f, 0x93, 0xa9, 0x66, 0x80, 0x43, 0x88, 0xfd, 0xd2, 0xaa, 0x53, 0xe6, 0xf0, 0xd5, 0x7d,
	0x32, 0xd5, 0x61, 0x9d, 0x9f, 0x81, 0x0c, 0x5a, 0x44, 0x90, 0xdc, 0x4d, 0x70, 0x37, 0xfe, 0xcf,
	0xc7, 0x10, 0xcf, 0xfe, 0x46, 0x21, 0xac, 0x59, 0x7a, 0xaa, 0x55, 0x94, 0xc5, 0x45, 0x57, 0xb7,
	0xc3, 0xf5, 0x25, 0xc8, 0x70, 0xa9, 0x98, 0x80, 0x98, 0xf7, 0xff, 0x61, 0x07, 0xe4, 0x13, 0xad,
	0xcb, 0xbe, 0xc0, 0x14, 0x8e, 0x34, 0x2d, 0xc8, 0x6e, 0xa9, 0x1f, 0x3d, 0xff, 0xe7, 0x47, 0xba,
	0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x88, 0x5d, 0x81, 0xb9, 0x01, 0x00, 0x00,
}
